name: Documentation Generation

on: push

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Compile Docs
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./source
          output_dir: ./source/docs/jsdocs
          template: minami
          front_page: README.md
          recurse: true
      
      - name: Commit and Push
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Update JSDocs from Github Actions (workflow name here)'